name: AWS prod pipeline

on:
  push:
    tags:
      - '@wowissu/eslint-config-v*'

jobs:
  buildAndPublish:
    name: BuildAndPublish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: publish
      run: node publish.js ./eslint


