name: '@wowissu/eslint-config publisher'

on:
  push:
    branchs:
      publisher
    tags:
      - '@wowissu/eslint-config-v*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'

    - name: yarn install
      run: yarn install

    - name: do publish
      run: node publisher.js ./eslint
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}


