name: '@wowissu/eslint-config publisher'

on:
  push:
    tags:
      - '@wowissu/eslint-config-v*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: yarn install
      run: yarn install

    - name: do publish
      run: |
        cd ./eslint
        yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

    - name: Discord successed notification
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "@wowissu/eslint-config"
        DISCORD_AVATAR: "https://avatars.githubusercontent.com/u/12434914?v=4"
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: 'The project `{{ GITHUB_REF_NAME }}` has been deployed. :thumbsup:'

    - name: Discord failed notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "@wowissu/eslint-config"
        DISCORD_AVATAR: "https://avatars.githubusercontent.com/u/12434914?v=4"
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: 'The project `{{ GITHUB_REF_NAME }}` is failed in publishing. :space_invader:'




